services:
  web:
    build:
      context: .
    depends_on:
      - docker
    command: flask run
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      DOCKER_HOST: tcp://docker:2375
    ports:
      - 5000:5000
    develop:
      watch:
        - action: rebuild
          path: app.py
    volumes:
      - data:/data

  docker:
    image: docker:dind
    privileged: true
    entrypoint: dockerd --host tcp://0.0.0.0:2375
    volumes:
      - data:/data

volumes:
  data: {}
